[package]
name = "card_dealer"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
warp = "0.3.7"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0.216", features = ["derive"] }
itertools = "0.13.0"
serde_json = "1.0"
